# Generated by Django 5.2.7 on 2025-11-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the cryptocurrency (e.g., Bitcoin)', max_length=100)),
                ('symbol', models.CharField(help_text='Ticker symbol (e.g., BTC)', max_length=10, unique=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, help_text='Current price', max_digits=20, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalization', null=True)),
                ('last_updated', models.DateTimeField(blank=True, help_text='Time of last data update', null=True)),
            ],
        ),
    ]
