# Generated by Django 5.2.7 on 2025-12-11 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('percent_change_1h', models.FloatField(blank=True, null=True)),
                ('percent_change_24h', models.FloatField(blank=True, null=True)),
                ('percent_change_7d', models.FloatField(blank=True, null=True)),
                ('percent_change_30d', models.FloatField(blank=True, null=True)),
                ('percent_change_60d', models.FloatField(blank=True, null=True)),
                ('percent_change_90d', models.FloatField(blank=True, null=True)),
                ('market_dominance', models.FloatField(blank=True, null=True)),
                ('circulating_supply', models.FloatField(blank=True, null=True)),
                ('total_supply', models.FloatField(blank=True, null=True)),
                ('max_supply', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.cryptoasset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
