# Generated by Django 5.2.5 on 2025-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(help_text='Full name of the cryptocurrency', max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(help_text='Ticker symbol', max_length=10, unique=True),
        ),
    ]
