# Generated by Django 5.2.7 on 2025-11-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cryptoasset_cryptoprice'),
        ('users', '0002_remove_userprofile_followed_cryptos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.cryptoasset'),
        ),
    ]
