# Generated by Django 5.2.5 on 2025-11-13 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=20)),
                ('to_currency', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('result', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Crypto Conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
