# Generated by Django 5.2.7 on 2025-11-18 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cryptoasset_cryptoprice'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followed_cryptos',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_crypto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_of', to='api.cryptoasset'),
        ),
        migrations.CreateModel(
            name='UserCryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='api.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'crypto')},
            },
        ),
    ]
